### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by ptman** [edbizarro/pgbouncer#1]
You seem to have just forked https://github.com/silverlogic/ansible-pgbouncer and changed the license from Apache-2.0 to MIT ( https://github.com/edbizarro/pgbouncer/commit/8762c49e3f603fbc4ba35f3b074ccdd9f8cc39f9#diff-9b4ddf055111f4371f04fbb8b5366655R4 ) . Are you sure @ryanpineo is ok with that?

**Comment by edbizarro** [comment]
hi @ptman 

I did not pay attention to it, I changed to have the same license.

this really is a fork with some fixes, improvements and additional options like ignore_startup_parameters

**Comment by ptman** [comment]
Thanks
